### ISSUE TITLE
v0.18.1 fails to compile with wasm-bindgen 0.2.113 / web-sys 0.3.90

### ISSUE THREAD

**Issue by emilbonnek** [Synphonyte/leptos-use#294]
## Summary

Version 0.18.1 fails to compile with `wasm-bindgen` 0.2.113 / `web-sys` 0.3.90 due to breaking API changes.

Both `leptos-use` v0.18.1 and `wasm-bindgen` v0.2.113 were released on the same day (February 24, 2026), and the API changes in wasm-bindgen introduced type mismatches that break leptos-use compilation.

## Reproduction

Minimal reproduction repository: https://github.com/emilbonnek/leptos-use-compilation-issue

```bash
git clone https://github.com/emilbonnek/leptos-use-compilation-issue
cd leptos-use-compilation-issue
cargo check --target wasm32-unknown-unknown
```

## Compilation Errors

**Total:** 24 compilation errors across 3 modules

### 1. Geolocation API (`use_geolocation`)

**Location:** `src/use_geolocation.rs:106`

**Error:**
```
error[E0308]: mismatched types
expected `i32`, found `Result<i32, JsValue>`
```

**Root cause:** `Geolocation::watch_position_with_error_callback_and_options()` now returns `Result<i32, JsValue>` instead of `i32`.

**Fix needed:** Handle the Result type with `.ok()`, `?`, or `.expect()`.

### 2. Scroll API (`use_scroll`)

**Locations:** `src/use_scroll.rs:313, 314, 317, 318`

**Errors:**
```
error[E0308]: mismatched types
expected `i32`, found floating-point number

error[E0277]: cannot add `f64` to `i32`
```

**Root cause:** Scroll properties (`scroll_left`, `scroll_top`, etc.) now return `f64` instead of `i32`.

**Fix needed:** Cast or update type annotations to handle `f64` values.

### 3. Mouse Events (`use_mouse`)

**Locations:** `src/use_mouse.rs:275, 276, 277`

**Errors:**
```
error[E0308]: mismatched types
expected `f64`, found `i32`
```

**Root cause:** Mouse coordinate methods (`page_x()`, `page_y()`, `client_x()`, `client_y()`, `screen_x()`, `screen_y()`) have return type mismatches between what leptos-use expects and what web-sys now provides.

**Fix needed:** Convert `i32` values to `f64` with `.into()` or `as f64`.

## Context

Version 0.18.1 included these commits attempting to fix Geolocation API issues:
- [4b32745](https://github.com/Synphonyte/leptos-use/commit/4b32745521f8997045b7423731dcd864d2e5664b) - Added `GeolocationPosition` and `GeolocationPositionError` web-sys features
- [3cd2f94](https://github.com/Synphonyte/leptos-use/commit/3cd2f94aafaea34ab871b1d087b49ddec34eb158) - Updated web-sys minimum to 0.3.86

However, these fixes were insufficient for the breaking changes introduced in wasm-bindgen 0.2.113.

## Environment

- **Rust:** 1.95.0-nightly (2026-02-16)
- **wasm-bindgen:** 0.2.113
- **web-sys:** 0.3.90
- **leptos-use:** 0.18.1
- **leptos:** 0.8.16

## Related Links

- wasm-bindgen v0.2.113 release: https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.113
- wasm-bindgen CHANGELOG: https://github.com/rustwasm/wasm-bindgen/blob/main/CHANGELOG.md
- leptos-use v0.18.1 release: https://github.com/Synphonyte/leptos-use/releases/tag/v0.18.1
