### ISSUE TITLE
Fix breakage caused by web-sys 0.3.104

### ISSUE THREAD

**Issue by EvanCarroll** [Synphonyte/leptos-use#325]
Fix breakage caused by https://github.com/wasm-bindgen/wasm-bindgen/pull/5246

> * Unstable API overload names now elide name tokens shared by every overload
  variant: `LockManager::request_with_callback` is now `request`, and
  `request_with_options_and_callback` is now `request_with_options`.

Currently it build fails using web-sys 0.3.104

```
error[E0599]: no method named `request_with_options_and_callback` found for struct `LockManager` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-use-0.19.0/src/use_web_lock.rs:106:14
    |
103 |           let lock_promise = window()
    |  ____________________________-
104 | |             .navigator()
105 | |             .locks()
106 | |             .request_with_options_and_callback(
    | |_____________-^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: there is a method `request_with_options` with a similar name
    |
106 -             .request_with_options_and_callback(
106 +             .request_with_options(
```
