### PR TITLE
fix(use_web_lock): track web-sys 0.3.104

### LINKED ISSUE #325: Fix breakage caused by web-sys 0.3.104
Fix breakage caused by https://github.com/wasm-bindgen/wasm-bindgen/pull/5246

> * Unstable API overload names now elide name tokens shared by every overload
  variant: `LockManager::request_with_callback` is now `request`, and
  `request_with_options_and_callback` is now `request_with_options`.

Currently it build fails using web-sys 0.3.104

```
error[E0599]: no method named `request_with_options_and_callback` found for struct `LockManager` in the current scope
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-use-0.19.0/src/use_web_lock.rs:106:14
    |
103 |           let lock_promise = window()
    |  ____________________________-
104 | |             .navigator()
105 | |             .locks()
106 | |             .request_with_options_and_callback(
    | |_____________-^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: there is a method `request_with_options` with a similar name
    |
106 -             .request_with_options_and_callback(
106 +             .request_with_options(
```

### PR DESCRIPTION
**Pull request by EvanCarroll**
Closes #325 

LockManager renames cause breakage.

web-sys 0.3.104 renamed the Web Locks bindings, dropping the overload disambiguator now that the callback is a typed js_sys::Function rather than an untyped one:

    request_with_callback              -> request
    request_with_options_and_callback  -> request_with_options

Both spellings are gated behind --cfg=web_sys_unstable_apis, and unstable web-sys APIs are exempt from semver, so this landed in a patch release and broke every downstream build that resolved 0.3.104:

    error[E0599]: no method named `request_with_options_and_callback`
    found for struct `LockManager` in the current scope

Rename the call site and raise the web-sys floor to ^0.3.104. The floor bump is the part that actually fixes it — under the old ^0.3.89 Cargo can still resolve 0.3.103, where `request_with_options` does not exist, which would leave the crate broken in the other direction.

### CODE REVIEW

**Comment by maccesch** [comment]
Nice work, thanks!
